### ISSUE TITLE
Ember serve hangs forever

### ISSUE THREAD

**Issue by orf** [n1ru4l/ember-cli-css-preprocess#2]
Hey,
After including this addon my `ember serve` just hangs forever. My config looked like this:

```
styleProcessorOptions: {
            processors: [{
                type: 'postcss',
                plugins: postcssPlugins
            }],
            extension: 'css'
        },
```

Where `postcssPlugins` contains `autoprefixer`, `postcss-simple-extend` and `postcss-import` modules. I also have only 6 small CSS files, included via `postcss-import` into `app.css`

**Comment by n1ru4l** [comment]
Could you please give me the whole configuration so that i could reproduce it?

**Comment by n1ru4l** [comment]
I was able to reproduce it by importing a non-existing stylesheet, i used the following configuration:

``` javascript
styleProcessorOptions: {
            processors: [{
                type: 'postcss',
                plugins: [
                    {
                        module: require('autoprefixer'),
                        options: {
                            browsers: ['last 2 versions']
                        }
                    },
                    {
                        module: require('postcss-import'),
                        options: {
                            from: 'app/styles/app.css'
                        }
                    },
                    {
                        module: require('postcss-simple-extend')
                    }
                ]
            }],
            extension: 'css'
        }
```

For now I fixed the freezing and the error output by a simple catch and console.log statement.
For the future I definitely want a correct error handling the broccoli way.
This will be added to the ToDo-list.

I hope I could help you with your problem, otherwise I'll need more information about your configuration

**Comment by n1ru4l** [comment]
Errors should now displayed and handled correctly (e87539dff6c0fcccb9f355dd690546e6527ebe67)

**Comment by n1ru4l** [comment]
Closed due to missing feedback
