### ISSUE TITLE
Importing files with PostCSS

### ISSUE THREAD

**Issue by kenips** [n1ru4l/ember-cli-css-preprocess#7]
Do I import other css files using regular `@import` rules when using PostCSS as my pre-processor?

1. I don't see other files being output once I add `ember-cli-css-preprocess`.
2. If I use additional PostCSS plugins (like normalize) then import rules are not defined at the top of the file.

What's the best way of importing files when using PostCSS? Should not not expect all css to be generated in the final output just as vanilla CSS? (I wouldn't expect the same when using SASS)

Thanks!

**Comment by n1ru4l** [comment]
By default postCSS does not support importing. This requires the postCSS-plugin [postcss-partial-import](https://github.com/jonathantneal/postcss-partial-import) or [postcss-import](https://github.com/postcss/postcss-import)

[This issue](https://github.com/n1ru4l/ember-cli-css-preprocess/issues/6) could probably answer your question.

There is no best way, there are many. I would recommend  [postcss-import](https://github.com/postcss/postcss-import) if you want to stick to postCSS otherwise a sass processor which supports `@import`-rules natively would also work (with less configuration).
